import type { ChartSettings, NumberFormat } from '../state/project';
import type { DataTable } from '../types';
import { formatChartValue, palettes } from '../charts/config';
import { parseNumericValue } from '../data/parser';
import type { ExportOptions } from './exporter';

type SeriesRef = number | string;

function background(settings:ChartSettings,options:ExportOptions){if(options.background==='transparent')return 'transparent';if(options.background==='white')return '#ffffff';return settings.background||palettes[settings.theme].background;}
function sourceColumns(table:DataTable){return table.headers.slice(1).map((_,index)=>index+1);}
function seriesId(table:DataTable,column:number){return table.columnIds?.[column]??String(column);}
function resolveRefs(table:DataTable,refs:SeriesRef[]|null|undefined){const cols=sourceColumns(table);return(refs??[]).map(ref=>typeof ref==='number'?ref:table.columnIds?.indexOf(ref)??-1).filter(column=>cols.includes(column));}
function readMap<T>(table:DataTable,map:Record<string,T>|undefined,column:number){return map?.[seriesId(table,column)]??map?.[String(column)];}
function orderedColumns(table:DataTable,settings:ChartSettings){const cols=sourceColumns(table),ordered=resolveRefs(table,settings.seriesOrder);return[...ordered,...cols.filter(column=>!ordered.includes(column))].filter(column=>!resolveRefs(table,settings.hiddenColumns).includes(column));}
function numeric(table:DataTable,column:number){return table.rows.map(row=>parseNumericValue(row[column]).value??0);}
function isPercentColumn(table:DataTable,column:number){return table.rows.some(row=>String(row[column]??'').trim().endsWith('%'));}
function valueFormatter(settings:ChartSettings,format: NumberFormat=settings.numberFormat,decimals=settings.decimals){return(value:number)=>`${settings.valuePrefix??''}${formatChartValue(value,format,decimals)}${settings.valueSuffix??''}`;}
function seriesName(table:DataTable,settings:ChartSettings,column:number){return readMap(table,settings.seriesNames,column)||table.headers[column];}
function seriesColor(table:DataTable,settings:ChartSettings,column:number){const palette=palettes[settings.theme].colors;return readMap(table,settings.seriesColors,column)??settings.customColors[column-1]??palette[(column-1)%palette.length];}
function dataLabels(settings:ChartSettings){return{show:settings.showDataLabels,position:settings.dataLabelPosition==='center'?'inside':'top',rotate:settings.dataLabelRotation,color:settings.dataLabelColor||undefined,fontSize:settings.dataLabelFontSize};}
function axes(table:DataTable,settings:ChartSettings,cols:number[],rightCols:number[]=[]){const palette=palettes[settings.theme],format=valueFormatter(settings,settings.numberFormat,settings.yAxisDecimals??settings.decimals),rightFormat=settings.rightAxisFormat==='auto'?settings.numberFormat:settings.rightAxisFormat;const percentLeft=settings.percentageStacked||(cols.length>0&&cols.every(column=>isPercentColumn(table,column))),percentRight=rightCols.length>0&&rightCols.every(column=>isPercentColumn(table,column));const x={type:'category',data:table.rows.map(row=>row[0]),name:settings.xAxisTitle,axisLabel:{rotate:settings.xLabelRotation,color:settings.xAxisColor||palette.text,fontSize:settings.xAxisFontSize},axisLine:{show:settings.showAxisBorder},splitLine:{show:false}};const y={type:settings.yScaleType==='logarithmic'?'log':'value',name:settings.yAxisTitle,inverse:settings.yReverse,min:settings.yMin??undefined,max:settings.yMax??undefined,axisLabel:{color:settings.yAxisColor||palette.text,fontSize:settings.yAxisFontSize,formatter:(value:number)=>percentLeft?`${((settings.percentageStacked?value:value*100)).toFixed(Math.max(1,settings.yAxisDecimals??settings.decimals))}%`:format(value)},axisLine:{show:settings.showAxisBorder},splitLine:{show:settings.showGrid,lineStyle:{color:palette.grid,width:settings.gridLineWidth}}};const y2={type:settings.y2ScaleType==='logarithmic'?'log':'value',name:settings.rightAxisTitle,inverse:settings.y2Reverse,min:settings.y2Min??undefined,max:settings.y2Max??undefined,axisLabel:{color:settings.y2AxisColor||palette.text,fontSize:settings.y2AxisFontSize,formatter:(value:number)=>percentRight?`${(value*100).toFixed(Math.max(1,settings.y2AxisDecimals??settings.decimals))}%`:valueFormatter(settings,rightFormat as NumberFormat,settings.y2AxisDecimals??settings.decimals)(value)},axisLine:{show:settings.showAxisBorder},splitLine:{show:false}};return{xAxis:settings.horizontal?y:x,yAxis:rightCols.length?[settings.horizontal?x:y,y2]:settings.horizontal?x:y};}
function common(table:DataTable,settings:ChartSettings,options:ExportOptions){const palette=palettes[settings.theme];return{backgroundColor:background(settings,options),color:orderedColumns(table,settings).map(column=>seriesColor(table,settings,column)),title:{text:settings.title,subtext:settings.subtitle,left:settings.titleAlign==='start'?'left':settings.titleAlign==='end'?'right':'center',textStyle:{color:settings.titleColor||palette.text,fontSize:settings.titleFontSize},subtextStyle:{color:settings.subtitleColor||palette.text,fontSize:settings.subtitleFontSize}},legend:{show:settings.showLegend,top:settings.legendPosition==='top'?42:undefined,bottom:settings.legendPosition==='bottom'?8:undefined,left:settings.legendPosition==='left'?8:undefined,right:settings.legendPosition==='right'?8:undefined,textStyle:{color:palette.text,fontSize:settings.legendFontSize}},tooltip:{show:false},animation:false,grid:{top:settings.plotMarginTop??(settings.subtitle?92:78),right:settings.plotMarginRight??(settings.type==='combo'?72:32),bottom:settings.plotMarginBottom??(settings.source?54:34),left:settings.plotMarginLeft??58,containLabel:true},graphic:settings.source?[{type:'text',left:24,bottom:14,style:{text:`数据来源：${settings.source}`,fill:palette.text,opacity:.62,font:'12px sans-serif'}}]:[]};}
function linearSeries(table:DataTable,settings:ChartSettings,type:'bar'|'line'|'area'){const cols=orderedColumns(table,settings),raw=cols.map(column=>numeric(table,column));const positive=table.rows.map((_,rowIndex)=>raw.reduce((sum,series)=>sum+Math.max(0,series[rowIndex]),0)),negative=table.rows.map((_,rowIndex)=>raw.reduce((sum,series)=>sum+Math.abs(Math.min(0,series[rowIndex])),0));return cols.map((column,seriesIndex)=>{const color=seriesColor(table,settings,column),isLine=type!=='bar',data=settings.percentageStacked?raw[seriesIndex].map((value,rowIndex)=>{const total=value<0?negative[rowIndex]:positive[rowIndex];return total?value/total*100:0;}):raw[seriesIndex];return{name:seriesName(table,settings,column),type:isLine?'line':'bar',data,smooth:isLine&&settings.smooth,step:isLine&&settings.lineStepped?'middle':false,stack:settings.stacked||settings.percentageStacked?'total':undefined,symbolSize:readMap(table,settings.seriesPointRadii,column)??settings.pointRadius,lineStyle:{width:readMap(table,settings.seriesLineWidths,column)??settings.lineWidth,type:readMap(table,settings.seriesDashed,column)||settings.lineDash?'dashed':'solid',color},areaStyle:type==='area'||settings.areaFill?{opacity:.18,color}:undefined,itemStyle:{color,borderRadius:type==='bar'?settings.barRadius:0,opacity:readMap(table,settings.seriesOpacity,column)??1},label:dataLabels(settings)};});}
function comboSeries(table:DataTable,settings:ChartSettings){const cols=orderedColumns(table,settings),bars=new Set(resolveRefs(table,settings.comboBarColumns)),right=settings.comboRightAxisColumns===null?cols.filter(column=>!bars.has(column)):resolveRefs(table,settings.comboRightAxisColumns);return{right,series:cols.map(column=>{const isBar=bars.has(column),color=seriesColor(table,settings,column);return{name:seriesName(table,settings,column),type:isBar?'bar':'line',yAxisIndex:right.includes(column)?1:0,data:numeric(table,column),smooth:!isBar&&settings.smooth,stack:isBar&&settings.stacked?'total':undefined,symbolSize:isBar?0:readMap(table,settings.seriesPointRadii,column)??settings.pointRadius,lineStyle:{width:readMap(table,settings.seriesLineWidths,column)??settings.lineWidth,type:readMap(table,settings.seriesDashed,column)||settings.lineDash?'dashed':'solid',color},areaStyle:!isBar&&settings.areaFill?{opacity:.16,color}:undefined,itemStyle:{color,borderRadius:isBar?settings.barRadius:0,opacity:readMap(table,settings.seriesOpacity,column)??1},label:dataLabels(settings)};})};}
export function buildSvgChartOption(table:DataTable,settings:ChartSettings,options:ExportOptions){const base=common(table,settings,options),cols=orderedColumns(table,settings);if(settings.type==='pie'||settings.type==='doughnut'){return{...base,series:[{type:'pie',radius:settings.type==='doughnut'?[`${settings.pieCutout}%`,'72%']:'72%',startAngle:90-settings.pieRotation,avoidLabelOverlap:true,label:dataLabels(settings),data:table.rows.map(row=>({name:row[0],value:parseNumericValue(row[1]).value??0}))}]};}if(settings.type==='radar'){return{...base,radar:{indicator:table.rows.map(row=>({name:row[0]})),axisName:{color:palettes[settings.theme].text}},series:[{type:'radar',data:cols.map(column=>({name:seriesName(table,settings,column),value:numeric(table,column),areaStyle:settings.areaFill?{opacity:.16}:undefined}))}]};}if(settings.type==='scatter'||settings.type==='bubble'){const color=seriesColor(table,settings,1);return{...base,xAxis:{type:'value'},yAxis:{type:'value'},series:[{type:'scatter',name:`${table.headers[1]} / ${table.headers[2]}`,data:table.rows.map(row=>[parseNumericValue(row[1]).value??0,parseNumericValue(row[2]).value??0,parseNumericValue(row[3]).value??10]),symbolSize:(value:number[])=>settings.type==='bubble'?Math.max(8,Math.sqrt(Math.abs(value[2]??10))*3):8,itemStyle:{color},label:dataLabels(settings)}]};}if(settings.type==='heatmap'){const values=table.rows.flatMap((row,rowIndex)=>row.slice(1).map((value,colIndex)=>[colIndex,rowIndex,parseNumericValue(value).value??0]));const nums=values.map(item=>item[2] as number);return{...base,xAxis:{type:'category',data:table.headers.slice(1)},yAxis:{type:'category',data:table.rows.map(row=>row[0])},visualMap:{show:false,min:Math.min(...nums),max:Math.max(...nums),inRange:{color:['#eef3ff',seriesColor(table,settings,1)]}},series:[{type:'heatmap',data:values,label:dataLabels(settings)}]};}if(settings.type==='funnel'){return{...base,series:[{type:'funnel',top:80,bottom:40,label:dataLabels(settings),data:table.rows.map(row=>({name:row[0],value:parseNumericValue(row[1]).value??0}))}]};}if(settings.type==='waterfall'){let running=0;const values=numeric(table,1),starts=values.map(value=>{const start=running;running+=value;return start;});return{...base,...axes(table,settings,[1]),series:[{type:'bar',stack:'total',silent:true,itemStyle:{color:'transparent'},data:starts},{type:'bar',stack:'total',name:table.headers[1],data:values,itemStyle:{color:(item:any)=>item.value>=0?'#168a62':'#d64545'},label:dataLabels(settings)}]};}if(settings.type==='combo'){const combo=comboSeries(table,settings);return{...base,...axes(table,settings,cols.filter(column=>!combo.right.includes(column)),combo.right),series:combo.series};}const chartType=settings.type==='area'?'area':settings.type==='line'?'line':'bar';return{...base,...axes(table,settings,cols),series:linearSeries(table,settings,chartType)};}
export function normalizeSvgMarkup(svg:string){return svg.replace(/^<svg\b([^>]*)>/,(match,attributes:string)=>{let next=attributes;if(!/\sxmlns=/.test(next))next=` xmlns="http://www.w3.org/2000/svg"${next}`;if(!/\srole=/.test(next))next=` role="img"${next}`;return `<svg${next}>`;});}
export async function renderChartSvg(table:DataTable,settings:ChartSettings,options:ExportOptions):Promise<string>{const echarts=await import('echarts');const host=document.createElement('div');host.style.cssText=`position:fixed;left:-10000px;top:-10000px;width:${options.width}px;height:${options.height}px;`;document.body.appendChild(host);const chart=echarts.init(host,null,{renderer:'svg',width:options.width,height:options.height});chart.setOption(buildSvgChartOption(table,settings,options),true);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const svg=host.querySelector('svg')?.outerHTML??'';chart.dispose();host.remove();if(!svg)throw new Error('SVG 渲染失败');return normalizeSvgMarkup(svg);}
