import { describe,expect,it } from 'vitest';
import { buildChartConfig } from '../src/charts/config';
import { projectTemplates } from '../src/templates/library';
import type { ChartSettings } from '../src/state/project';

const base:ChartSettings={type:'bar',theme:'business',title:'测试',subtitle:'',source:'',xAxisTitle:'',yAxisTitle:'',legendPosition:'top',showLegend:true,showDataLabels:false,showGrid:true,animate:false,background:'#fff',numberFormat:'number',decimals:0,horizontal:false,stacked:false,smooth:true,areaFill:false,customColors:[],yMin:null,yMax:null,yStep:null,valuePrefix:'',valueSuffix:'',percentageStacked:false,connectGaps:false,pieCutout:55,pieRotation:0,showTrendline:false,pieCenterText:'',pieMergeSmallThreshold:0,comboBarColumns:[1],rightAxisTitle:'',rightAxisFormat:'auto',y2Min:null,y2Max:null,y2Step:null,yBeginAtZero:true,y2BeginAtZero:true,comboRightAxisColumns:null,hiddenColumns:[],barCategoryPercentage:.8,barPercentage:.9,barRadius:5,barBorderWidth:0,lineWidth:2,lineDash:false,pointRadius:4,xLabelRotation:0,dataLabelPosition:'auto',lineStepped:false,xMaxTicks:12,showAxisBorder:true,gridLineWidth:1,seriesNames:{},seriesOrder:[],seriesOpacity:{},seriesLineWidths:{},seriesPointRadii:{},seriesDashed:{},xAxisFontSize:11,xAxisColor:'',yAxisFontSize:11,yAxisColor:'',yAxisDecimals:null,y2AxisFontSize:11,y2AxisColor:'',y2AxisDecimals:null,titleFontSize:18,titleColor:'',titleAlign:'center',subtitleFontSize:12,subtitleColor:'',legendFontSize:11,legendPointStyle:'circle',legendReverse:false,dataLabelFontSize:10,dataLabelColor:'',dataLabelBackground:'',dataLabelBorderColor:'',plotPadding:8,plotBorderWidth:0,plotBorderColor:'',seriesPointStyles:{},seriesTrendlines:{},seriesMovingAveragePeriods:{},showTrendEquation:true,showTrendR2:true,yScaleType:'linear',y2ScaleType:'linear',yReverse:false,y2Reverse:false,dataLabelRotation:0,dataLabelOffset:0};
const table={headers:['项目','数值A','数值B','规模'],rows:[['A','10','20','9'],['B','-4','18','16']]};

describe('professional charts',()=>{
  it('supports independent plot margins and layout presets',()=>{const config:any=buildChartConfig(table,{...base,plotMarginTop:11,plotMarginRight:22,plotMarginBottom:33,plotMarginLeft:44});expect(config.options.layout.padding).toEqual({top:11,right:22,bottom:33,left:44});});
  it('builds combo chart with a secondary axis',()=>{const config:any=buildChartConfig(table,{...base,type:'combo'});expect(config.data.datasets[0].type).toBe('bar');expect(config.data.datasets[1].type).toBe('line');expect(config.options.scales.y1.position).toBe('right');const sameAxis:any=buildChartConfig(table,{...base,type:'combo',comboRightAxisColumns:[]});expect(sameAxis.data.datasets[1].type).toBe('line');expect(sameAxis.data.datasets[1].yAxisID).toBe('y');expect(sameAxis.options.scales.y1.display).toBe(false);const allLine:any=buildChartConfig(table,{...base,type:'combo',comboBarColumns:[]});expect(allLine.data.datasets.every((dataset:any)=>dataset.type==='line')).toBe(true);const percent:any=buildChartConfig({headers:['项目','金额','完成率'],rows:[['A','10','15%'],['B','20','20%']]},{...base,type:'combo'});expect(percent.data.datasets[1].valueFormatter(0.15)).toBe('15.0%');expect(percent.options.scales.y1.ticks.callback(0.15)).toBe('15.0%');expect(percent.options.scales.y1.max).toBe(1);expect(percent.options.scales.y1.title.text).toBe('完成率');const switched:any=buildChartConfig({headers:['项目','金额','完成率'],rows:[['A','10','15%']]},{...base,type:'combo',comboBarColumns:[2],rightAxisFormat:'percent',y2Max:60,y2Step:10,y2BeginAtZero:false,y2ScaleType:'logarithmic',y2Reverse:true});expect(switched.data.datasets[0].type).toBe('line');expect(switched.data.datasets[1].type).toBe('bar');expect(switched.options.scales.y.max).toBe(1);expect(switched.options.scales.y1.max).toBe(.6);expect(switched.options.scales.y1.ticks.stepSize).toBeUndefined();expect(switched.options.scales.y1.beginAtZero).toBe(false);expect(switched.options.scales.y1.type).toBe('logarithmic');expect(switched.options.scales.y1.reverse).toBe(true);});
  it('builds bubble and waterfall datasets',()=>{const bubble:any=buildChartConfig(table,{...base,type:'bubble'});expect(bubble.type).toBe('bubble');expect(bubble.data.datasets[0].data[0].r).toBeGreaterThan(0);const waterfall:any=buildChartConfig(table,{...base,type:'waterfall'});expect(waterfall.data.datasets[0].data[0]).toEqual([0,10]);expect(waterfall.data.datasets[0].data[1]).toEqual([10,6]);});
  it('applies Excel-style bar and line appearance',()=>{const bar:any=buildChartConfig(table,{...base,type:'bar',barCategoryPercentage:.6,barPercentage:.7,barRadius:9,barBorderWidth:2,hiddenColumns:[1],xLabelRotation:45,seriesOrder:[2,1],seriesNames:{'2':'利润'},seriesOpacity:{'2':.5},xAxisFontSize:14,xAxisColor:'#112233',yAxisFontSize:13,yAxisColor:'#334455',yAxisDecimals:2,yScaleType:'logarithmic',yReverse:true,dataLabelRotation:45,dataLabelOffset:8,titleFontSize:24,titleColor:'#101010',titleAlign:'start',legendFontSize:13,legendPointStyle:'rect',legendReverse:true,plotPadding:20,plotBorderWidth:2,plotBorderColor:'#999999'});expect(bar.data.datasets[0].label).toBe('利润');expect(bar.data.datasets[0].backgroundColor).toContain('0.5');expect(bar.data.datasets[0].categoryPercentage).toBe(.6);expect(bar.data.datasets[0].borderRadius).toBe(9);expect(bar.data.datasets[1].hidden).toBe(true);expect(bar.options.scales.x.ticks.maxRotation).toBe(45);expect(bar.options.scales.x.ticks.font.size).toBe(14);expect(bar.options.scales.y.ticks.color).toBe('#334455');expect(bar.options.scales.y.ticks.callback(1)).toBe('1.00');expect(bar.options.scales.y.type).toBe('logarithmic');expect(bar.options.scales.y.reverse).toBe(true);expect(bar.options.plugins.workspaceDataLabels.rotation).toBe(45);expect(bar.options.plugins.title.font.size).toBe(24);expect(bar.options.plugins.title.align).toBe('start');expect(bar.options.plugins.legend.labels.pointStyle).toBe('rect');expect(bar.options.plugins.legend.reverse).toBe(true);expect(bar.options.layout.padding).toBe(20);expect(bar.options.plugins.workspacePlotFrame.width).toBe(2);const line:any=buildChartConfig(table,{...base,type:'line',lineWidth:4,lineDash:true,lineStepped:true,pointRadius:6,seriesLineWidths:{'1':5},seriesPointRadii:{'1':7},seriesDashed:{'1':false},seriesPointStyles:{'1':'triangle'},seriesTrendlines:{'1':'linear'},xMaxTicks:7,showAxisBorder:false,gridLineWidth:2});expect(line.data.datasets[0].borderWidth).toBe(5);expect(line.data.datasets[0].borderDash).toEqual([]);expect(line.data.datasets[0].pointRadius).toBe(7);expect(line.data.datasets[0].pointStyle).toBe('triangle');expect(line.data.datasets).toHaveLength(4);expect(line.data.datasets[3].label).toMatch(/y=.*R²=/);expect(line.data.datasets[3].skipDataLabels).toBe(true);expect(line.data.datasets[1].borderDash).toEqual([8,5]);expect(line.data.datasets[0].stepped).toBe(true);expect(line.options.scales.x.ticks.maxTicksLimit).toBe(7);expect(line.options.scales.y.border.display).toBe(false);expect(line.options.scales.y.grid.lineWidth).toBe(2);const percentLine:any=buildChartConfig({headers:['项目','完成率'],rows:[['A','15%'],['B','30%']]},{...base,type:'line'});expect(percentLine.data.datasets[0].valueFormatter(.15)).toBe('15.0%');expect(percentLine.options.scales.y.ticks.callback(.15)).toBe('15.0%');});
  it('builds polynomial and moving-average trendlines',()=>{const trendTable={headers:['项目','A','B'],rows:[['一','1','3'],['二','4','5'],['三','9','7']]};const config:any=buildChartConfig(trendTable,{...base,type:'line',seriesTrendlines:{'1':'polynomial','2':'movingAverage'},seriesMovingAveragePeriods:{'2':2}});expect(config.data.datasets).toHaveLength(4);expect(config.data.datasets[2].label).toMatch(/x².*R²=/);expect(config.data.datasets[3].label).toContain('移动平均(2)');expect(config.data.datasets[3].data[0]).toBeNull();});
  it('applies custom brand colors',()=>{const config:any=buildChartConfig(table,{...base,type:'bar',customColors:['#123456']});expect(config.data.datasets[0].backgroundColor).toBe('rgba(18,52,86,1)');});
  it('supports percentages, pie rotation and a regression line',()=>{const stacked:any=buildChartConfig(table,{...base,type:'bar',stacked:true,percentageStacked:true});expect(stacked.data.datasets[0].data[0]).toBeCloseTo(10/39*100);expect(stacked.data.datasets[0].data[1]).toBe(-100);expect(stacked.options.scales.y.min).toBe(-100);const pie:any=buildChartConfig(table,{...base,type:'doughnut',pieRotation:90,pieCutout:60,background:'#f0f1f2'});expect(pie.options.rotation).toBeCloseTo(Math.PI/2);expect(pie.options.cutout).toBe('60%');expect(pie.data.datasets[0].borderColor).toBe('#f0f1f2');const scatter:any=buildChartConfig(table,{...base,type:'scatter',showTrendline:true});expect(scatter.data.datasets).toHaveLength(2);});
  it('builds heatmap and funnel visual datasets',()=>{const heat:any=buildChartConfig(table,{...base,type:'heatmap'});expect(heat.type).toBe('scatter');expect(heat.data.datasets[0].data.length).toBeGreaterThan(0);const funnel:any=buildChartConfig(table,{...base,type:'funnel'});expect(funnel.options.indexAxis).toBe('y');});
});

describe('template library',()=>{it('contains usable, unique templates',()=>{expect(projectTemplates.length).toBeGreaterThanOrEqual(5);expect(new Set(projectTemplates.map(item=>item.id)).size).toBe(projectTemplates.length);for(const item of projectTemplates){expect(item.data.headers.length).toBeGreaterThan(1);expect(item.data.rows.length).toBeGreaterThan(0);}});});
