import { describe,expect,it } from 'vitest';
import { buildChartConfig } from '../src/charts/config';
import { projectTemplates } from '../src/templates/library';
import type { ChartSettings } from '../src/state/project';

const base:ChartSettings={type:'bar',theme:'business',title:'测试',subtitle:'',source:'',xAxisTitle:'',yAxisTitle:'',legendPosition:'top',showLegend:true,showDataLabels:false,showGrid:true,animate:false,background:'#fff',numberFormat:'number',decimals:0,horizontal:false,stacked:false,smooth:true,areaFill:false,customColors:[],yMin:null,yMax:null,yStep:null,valuePrefix:'',valueSuffix:'',percentageStacked:false,connectGaps:false,pieCutout:55,pieRotation:0,showTrendline:false,pieCenterText:'',pieMergeSmallThreshold:0,comboBarColumns:[1],rightAxisTitle:'',rightAxisFormat:'auto',y2Min:null,y2Max:null,y2Step:null,yBeginAtZero:true,y2BeginAtZero:true,comboRightAxisColumns:null,hiddenColumns:[],barCategoryPercentage:.8,barPercentage:.9,barRadius:5,barBorderWidth:0,lineWidth:2,lineDash:false,pointRadius:4,xLabelRotation:0,dataLabelPosition:'auto'};
const table={headers:['项目','数值A','数值B','规模'],rows:[['A','10','20','9'],['B','-4','18','16']]};

describe('professional charts',()=>{
  it('builds area chart as a filled line chart',()=>{const config:any=buildChartConfig(table,{...base,type:'area'});expect(config.type).toBe('line');expect(config.data.datasets[0].fill).toBe(true);});
  it('builds combo chart with a secondary axis',()=>{const config:any=buildChartConfig(table,{...base,type:'combo'});expect(config.data.datasets[0].type).toBe('bar');expect(config.data.datasets[1].type).toBe('line');expect(config.options.scales.y1.position).toBe('right');const sameAxis:any=buildChartConfig(table,{...base,type:'combo',comboRightAxisColumns:[]});expect(sameAxis.data.datasets[1].type).toBe('line');expect(sameAxis.data.datasets[1].yAxisID).toBe('y');expect(sameAxis.options.scales.y1.display).toBe(false);const percent:any=buildChartConfig({headers:['项目','金额','完成率'],rows:[['A','10','15%'],['B','20','20%']]},{...base,type:'combo'});expect(percent.data.datasets[1].valueFormatter(0.15)).toBe('15.0%');expect(percent.options.scales.y1.ticks.callback(0.15)).toBe('15.0%');expect(percent.options.scales.y1.max).toBe(1);expect(percent.options.scales.y1.title.text).toBe('完成率');const switched:any=buildChartConfig({headers:['项目','金额','完成率'],rows:[['A','10','15%']]},{...base,type:'combo',comboBarColumns:[2],rightAxisFormat:'percent',y2Max:60,y2Step:10,y2BeginAtZero:false});expect(switched.data.datasets[0].type).toBe('line');expect(switched.data.datasets[1].type).toBe('bar');expect(switched.options.scales.y.max).toBe(1);expect(switched.options.scales.y1.max).toBe(.6);expect(switched.options.scales.y1.ticks.stepSize).toBe(.1);expect(switched.options.scales.y1.beginAtZero).toBe(false);});
  it('builds bubble and waterfall datasets',()=>{const bubble:any=buildChartConfig(table,{...base,type:'bubble'});expect(bubble.type).toBe('bubble');expect(bubble.data.datasets[0].data[0].r).toBeGreaterThan(0);const waterfall:any=buildChartConfig(table,{...base,type:'waterfall'});expect(waterfall.data.datasets[0].data[0]).toEqual([0,10]);expect(waterfall.data.datasets[0].data[1]).toEqual([10,6]);});
  it('applies Excel-style bar and line appearance',()=>{const bar:any=buildChartConfig(table,{...base,type:'bar',barCategoryPercentage:.6,barPercentage:.7,barRadius:9,barBorderWidth:2,hiddenColumns:[2],xLabelRotation:45});expect(bar.data.datasets[0].categoryPercentage).toBe(.6);expect(bar.data.datasets[0].borderRadius).toBe(9);expect(bar.data.datasets[1].hidden).toBe(true);expect(bar.options.scales.x.ticks.maxRotation).toBe(45);const line:any=buildChartConfig(table,{...base,type:'line',lineWidth:4,lineDash:true,pointRadius:6});expect(line.data.datasets[0].borderWidth).toBe(4);expect(line.data.datasets[0].borderDash).toEqual([8,5]);expect(line.data.datasets[0].pointRadius).toBe(6);const percentLine:any=buildChartConfig({headers:['项目','完成率'],rows:[['A','15%'],['B','30%']]},{...base,type:'line'});expect(percentLine.data.datasets[0].valueFormatter(.15)).toBe('15.0%');expect(percentLine.options.scales.y.ticks.callback(.15)).toBe('15.0%');});
  it('applies custom brand colors',()=>{const config:any=buildChartConfig(table,{...base,type:'bar',customColors:['#123456']});expect(config.data.datasets[0].backgroundColor).toBe('#123456');});
  it('supports percentages, pie rotation and a regression line',()=>{const stacked:any=buildChartConfig(table,{...base,type:'bar',stacked:true,percentageStacked:true});expect(stacked.data.datasets[0].data[0]).toBeCloseTo(10/39*100);expect(stacked.data.datasets[0].data[1]).toBe(-100);expect(stacked.options.scales.y.min).toBe(-100);const pie:any=buildChartConfig(table,{...base,type:'doughnut',pieRotation:90,pieCutout:60,background:'#f0f1f2'});expect(pie.options.rotation).toBeCloseTo(Math.PI/2);expect(pie.options.cutout).toBe('60%');expect(pie.data.datasets[0].borderColor).toBe('#f0f1f2');const scatter:any=buildChartConfig(table,{...base,type:'scatter',showTrendline:true});expect(scatter.data.datasets).toHaveLength(2);});
  it('builds heatmap and funnel visual datasets',()=>{const heat:any=buildChartConfig(table,{...base,type:'heatmap'});expect(heat.type).toBe('scatter');expect(heat.data.datasets[0].data.length).toBeGreaterThan(0);const funnel:any=buildChartConfig(table,{...base,type:'funnel'});expect(funnel.options.indexAxis).toBe('y');});
});

describe('template library',()=>{it('contains usable, unique templates',()=>{expect(projectTemplates.length).toBeGreaterThanOrEqual(5);expect(new Set(projectTemplates.map(item=>item.id)).size).toBe(projectTemplates.length);for(const item of projectTemplates){expect(item.data.headers.length).toBeGreaterThan(1);expect(item.data.rows.length).toBeGreaterThan(0);}});});
