import {beforeEach,describe,expect,it,vi} from 'vitest';
import {createDefaultChartSettings,useProjectState} from '../src/state/project';

describe('stable column identities',()=>{
  beforeEach(()=>vi.stubGlobal('localStorage',{getItem:()=>null,setItem:()=>{},removeItem:()=>{},clear:()=>{},key:()=>null,length:0}));
  it('preserves identities while editing raw data and adding columns',()=>{const state=useProjectState(),before=[...(state.table.value.columnIds??[])];state.rawInput.value='项目\t数值\nA\t10\nB\t20';state.parseRaw();expect(state.table.value.columnIds).toEqual(before);state.addColumn();expect(state.table.value.columnIds).toHaveLength(3);expect(state.table.value.columnIds?.[2]).not.toBe(before[1]);});
  it('migrates legacy numeric bindings and keeps them after deletion',()=>{const state=useProjectState(),chart=createDefaultChartSettings();chart.seriesNames={'2':'利润'};chart.seriesOpacity={'2':.5};chart.seriesColors={'2':'#ff0000'};chart.hiddenColumns=[2];chart.comboBarColumns=[1];state.loadProject({headers:['项目','销售额','利润'],rows:[['A','10','3']]},chart);const ids=state.table.value.columnIds!;expect(state.settings.seriesNames[ids[2]]).toBe('利润');expect(state.settings.seriesColors?.[ids[2]]).toBe('#ff0000');expect(state.settings.hiddenColumns).toContain(ids[2]);state.deleteColumn(1);expect(state.table.value.columnIds?.[1]).toBe(ids[2]);expect(state.settings.seriesNames[ids[2]]).toBe('利润');expect(state.settings.seriesOpacity[ids[2]]).toBe(.5);expect(state.settings.seriesColors?.[ids[2]]).toBe('#ff0000');});
  it('creates fresh bindings when importing unrelated data',()=>{const state=useProjectState(),oldId=state.table.value.columnIds?.[1];state.settings.seriesNames[oldId!]='旧系列';state.loadTable({headers:['地区','收入'],rows:[['华东','20']]});expect(state.table.value.columnIds?.[1]).not.toBe(oldId);expect(state.settings.seriesNames).toEqual({});});
});
