<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { DataTable } from '../types';
import type { ChartSettings } from '../state/project';
import { buildChartConfig, palettes } from '../charts/config';
declare const Chart: new (context: CanvasRenderingContext2D, config: unknown) => { destroy():void; resize():void };
const props=defineProps<{table:DataTable;settings:ChartSettings;zoom:number;errorMessage:string}>();
const canvas=ref<HTMLCanvasElement>(); let instance:{destroy():void;resize():void}|null=null; let timer:number|undefined;
function render(){ window.clearTimeout(timer); timer=window.setTimeout(async()=>{await nextTick();instance?.destroy();instance=null;if(!canvas.value||props.errorMessage)return;const ctx=canvas.value.getContext('2d'); if(ctx)instance=new Chart(ctx,buildChartConfig(props.table,props.settings));},100); }
watch(()=>[props.table,props.settings.type,props.settings.theme,props.settings.title,props.settings.subtitle,props.settings.xAxisTitle,props.settings.yAxisTitle,props.settings.legendPosition,props.settings.showLegend,props.settings.showDataLabels,props.settings.showGrid,props.settings.animate,props.settings.numberFormat,props.settings.decimals,props.settings.horizontal,props.settings.stacked,props.settings.smooth,props.settings.areaFill,props.settings.customColors,props.settings.yMin,props.settings.yMax,props.settings.yStep,props.settings.valuePrefix,props.settings.valueSuffix,props.settings.percentageStacked,props.settings.connectGaps,props.settings.pieCutout,props.settings.pieRotation,props.settings.showTrendline,props.settings.pieCenterText,props.settings.pieMergeSmallThreshold,props.settings.background,props.errorMessage,props.settings.comboBarColumns,props.settings.rightAxisTitle,props.settings.rightAxisFormat,props.settings.y2Min,props.settings.y2Max,props.settings.y2Step,props.settings.yBeginAtZero,props.settings.y2BeginAtZero,props.settings.comboRightAxisColumns,props.settings.hiddenColumns,props.settings.barCategoryPercentage,props.settings.barPercentage,props.settings.barRadius,props.settings.barBorderWidth,props.settings.lineWidth,props.settings.lineDash,props.settings.pointRadius,props.settings.xLabelRotation,props.settings.dataLabelPosition,props.settings.lineStepped,props.settings.xMaxTicks,props.settings.showAxisBorder,props.settings.gridLineWidth,props.settings.seriesNames,props.settings.seriesOrder,props.settings.seriesOpacity,props.settings.seriesLineWidths,props.settings.seriesPointRadii,props.settings.seriesDashed,props.settings.xAxisFontSize,props.settings.xAxisColor,props.settings.yAxisFontSize,props.settings.yAxisColor,props.settings.yAxisDecimals,props.settings.y2AxisFontSize,props.settings.y2AxisColor,props.settings.y2AxisDecimals],render,{deep:true});
onMounted(render); onBeforeUnmount(()=>instance?.destroy());
function getPngDataUrl(){return canvas.value?.toDataURL('image/png',1)??null;}
function download(){if(!canvas.value)return;const link=document.createElement('a');link.download=`table-chart-${Date.now()}.png`;link.href=canvas.value.toDataURL('image/png',1);link.click();}
defineExpose({download,getPngDataUrl});
</script>
<template><main class="canvas-area"><div class="canvas-toolbar"><span>画布</span><span>{{ zoom }}%</span></div><div class="canvas-stage"><div class="chart-sheet" :style="{transform:`scale(${zoom/100})`,background:settings.background||palettes[settings.theme].background,color:palettes[settings.theme].text}"><div v-if="errorMessage" class="canvas-error"><strong>无法生成预览</strong><span>{{errorMessage}}</span></div><canvas v-show="!errorMessage" ref="canvas"></canvas><div v-if="settings.source&&!errorMessage" class="chart-source">数据来源：{{settings.source}}</div></div></div></main></template>
