<script setup lang="ts">
import { computed,reactive,ref,watch } from 'vue';
import { exportPresets,type ExportFormat,type ExportOptions } from '../export/exporter';
const props=defineProps<{projectName:string}>();const emit=defineEmits<{close:[];export:[options:ExportOptions]}>();
const form=reactive<ExportOptions>({format:'png',width:1600,height:900,scale:2,background:'theme',fileName:props.projectName,batch:false});
const lockRatio=ref(true),ratio=ref(form.width/form.height),updating=ref(false);
const pixels=computed(()=>`${form.width*form.scale} × ${form.height*form.scale} px`);
function preset(width:number,height:number){updating.value=true;form.width=width;form.height=height;ratio.value=width/height;updating.value=false;}
watch(()=>form.width,value=>{if(lockRatio.value&&!updating.value){updating.value=true;form.height=Math.max(240,Math.round(value/ratio.value));updating.value=false;}});
watch(()=>form.height,value=>{if(lockRatio.value&&!updating.value){updating.value=true;form.width=Math.max(320,Math.round(value*ratio.value));updating.value=false;}});
function submit(){if(form.format==='pdf'&&form.background==='transparent')form.background='white';emit('export',{...form,fileName:form.fileName.trim()||'chart'});}
</script>
<template><div class="modal-backdrop" @click.self="emit('close')"><section class="export-dialog"><header><div><span class="eyebrow">EXPORT</span><h3>导出图表</h3></div><button @click="emit('close')">×</button></header><div class="export-format"><button v-for="item in ([['png','PNG 图片'],['pdf','PDF 文档'],['csv','CSV 数据']] as [ExportFormat,string][])" :key="item[0]" :class="{active:form.format===item[0]}" @click="form.format=item[0]">{{item[1]}}</button></div><template v-if="form.format!=='csv'"><label class="export-label">尺寸预设</label><div class="preset-grid"><button v-for="item in exportPresets" :key="item.id" :class="{active:form.width===item.width&&form.height===item.height}" @click="preset(item.width,item.height)"><strong>{{item.label}}</strong><span>{{item.width}}×{{item.height}}</span></button></div><div class="dimension-row"><label>宽度<input type="number" min="320" max="8000" v-model.number="form.width"></label><button class="ratio-lock" :class="{active:lockRatio}" title="锁定宽高比" @click="lockRatio=!lockRatio">{{lockRatio?'锁定':'自由'}}</button><label>高度<input type="number" min="240" max="8000" v-model.number="form.height"></label></div><label class="export-label">输出倍率</label><div class="choice-row"><button v-for="scale in [1,2,3]" :key="scale" :class="{active:form.scale===scale}" @click="form.scale=scale">{{scale}}×</button><span>{{pixels}}</span></div><label class="export-label">背景</label><div class="choice-row"><button v-for="item in ([['theme','主题背景'],['white','白色'],['transparent','透明']] as const)" :key="item[0]" :disabled="form.format==='pdf'&&item[0]==='transparent'" :class="{active:form.background===item[0]}" @click="form.background=item[0]">{{item[1]}}</button></div></template><label v-if="form.format!=='csv'" class="batch-toggle"><input type="checkbox" v-model="form.batch"><span>按每个数值列批量生成图表</span></label><label class="export-label">文件名</label><input class="field export-name" v-model="form.fileName"><p class="export-capability">当前图表基于 Canvas 渲染，支持高清 PNG/PDF；暂不提供原生矢量 SVG。</p><footer><span v-if="form.format==='csv'">导出当前清洗后的数据</span><span v-else>按目标尺寸重新渲染，文字保持清晰</span><button class="primary-command" @click="submit">开始导出</button></footer></section></div></template>
