<script setup lang="ts">
import { ref } from 'vue';
import type { ChartType } from '../types';
import type { ChartSettings, LegendPosition, NumberFormat, ThemeName } from '../state/project';
import { palettes } from '../charts/config';
const props=defineProps<{settings:ChartSettings;numericColumns:number}>();
const emit=defineEmits<{change:[value:Partial<ChartSettings>]} >();
const tab=ref<'chart'|'style'|'text'>('chart');
const types:{value:ChartType;label:string;min:number}[]=[{value:'bar',label:'柱状',min:1},{value:'line',label:'折线',min:1},{value:'area',label:'面积',min:1},{value:'combo',label:'组合',min:2},{value:'pie',label:'饼图',min:1},{value:'doughnut',label:'环形',min:1},{value:'radar',label:'雷达',min:1},{value:'scatter',label:'散点',min:2},{value:'bubble',label:'气泡',min:3},{value:'waterfall',label:'瀑布',min:1},{value:'heatmap',label:'热力',min:2},{value:'funnel',label:'漏斗',min:1}];
const themes=Object.keys(palettes) as ThemeName[];
const legends:{value:LegendPosition;label:string}[]=[{value:'top',label:'顶部'},{value:'bottom',label:'底部'},{value:'left',label:'左侧'},{value:'right',label:'右侧'}];
const formats:{value:NumberFormat;label:string}[]=[{value:'number',label:'数字'},{value:'compact',label:'紧凑'},{value:'percent',label:'百分比'},{value:'currency',label:'人民币'}];
function updateCustomColor(index:number,color:string){const colors=[...props.settings.customColors];while(colors.length<=index)colors.push(palettes[props.settings.theme].colors[colors.length%palettes[props.settings.theme].colors.length]);colors[index]=color;emit('change',{customColors:colors});}
function resetCustomColors(){emit('change',{customColors:[]});}
</script>
<template><aside class="property-panel panel-shell"><div class="panel-heading"><div><span class="eyebrow">DESIGN</span><h2>属性</h2></div></div><div class="property-tabs"><button :class="{active:tab==='chart'}" @click="tab='chart'">图表</button><button :class="{active:tab==='style'}" @click="tab='style'">样式</button><button :class="{active:tab==='text'}" @click="tab='text'">文字</button></div>
<template v-if="tab==='chart'"><section class="property-section"><label>图表类型</label><div class="type-grid"><button v-for="item in types" :key="item.value" :disabled="numericColumns<item.min" :class="{active:settings.type===item.value}" @click="emit('change',{type:item.value})">{{item.label}}</button></div></section><section v-if="settings.type==='bar'" class="property-section toggles"><label><span>横向柱状</span><input type="checkbox" :checked="settings.horizontal" @change="emit('change',{horizontal:($event.target as HTMLInputElement).checked})"></label><label><span>数据堆叠</span><input type="checkbox" :checked="settings.stacked" @change="emit('change',{stacked:($event.target as HTMLInputElement).checked})"></label></section><section v-if="settings.type==='line'" class="property-section toggles"><label><span>平滑曲线</span><input type="checkbox" :checked="settings.smooth" @change="emit('change',{smooth:($event.target as HTMLInputElement).checked})"></label><label><span>面积填充</span><input type="checkbox" :checked="settings.areaFill" @change="emit('change',{areaFill:($event.target as HTMLInputElement).checked})"></label></section><section class="property-section"><label>图例位置</label><select class="field" :value="settings.legendPosition" @change="emit('change',{legendPosition:($event.target as HTMLSelectElement).value as LegendPosition})"><option v-for="item in legends" :key="item.value" :value="item.value">{{item.label}}</option></select></section><section class="property-section toggles"><label><span>显示图例</span><input type="checkbox" :checked="settings.showLegend" @change="emit('change',{showLegend:($event.target as HTMLInputElement).checked})"></label><label><span>显示数据标签</span><input type="checkbox" :checked="settings.showDataLabels" @change="emit('change',{showDataLabels:($event.target as HTMLInputElement).checked})"></label><label><span>显示网格线</span><input type="checkbox" :checked="settings.showGrid" @change="emit('change',{showGrid:($event.target as HTMLInputElement).checked})"></label><label><span>图表动画</span><input type="checkbox" :checked="settings.animate" @change="emit('change',{animate:($event.target as HTMLInputElement).checked})"></label></section></template>
<template v-else-if="tab==='style'"><section class="property-section"><label>专业配色</label><div class="palette-grid"><button v-for="theme in themes" :key="theme" :class="{active:settings.theme===theme}" :title="theme" @click="emit('change',{theme})"><i v-for="color in palettes[theme].colors.slice(0,4)" :key="color" :style="{background:color}"></i></button></div></section><section class="property-section"><label>品牌色</label><div class="brand-colors"><input v-for="index in 5" :key="index" type="color" :value="settings.customColors[index-1]||palettes[settings.theme].colors[index-1]" @input="updateCustomColor(index-1,($event.target as HTMLInputElement).value)"><button v-if="settings.customColors.length" @click="resetCustomColors">重置</button></div></section><section class="property-section"><label>数字格式</label><select class="field" :value="settings.numberFormat" @change="emit('change',{numberFormat:($event.target as HTMLSelectElement).value as NumberFormat})"><option v-for="item in formats" :key="item.value" :value="item.value">{{item.label}}</option></select></section><section class="property-section"><label>小数位 {{settings.decimals}}</label><input class="range-field" type="range" min="0" max="3" step="1" :value="settings.decimals" @input="emit('change',{decimals:Number(($event.target as HTMLInputElement).value)})"></section></template>
<template v-else><section class="property-section field-stack"><label>主标题<input class="field" :value="settings.title" @input="emit('change',{title:($event.target as HTMLInputElement).value})"></label><label>副标题<input class="field" :value="settings.subtitle" placeholder="可选" @input="emit('change',{subtitle:($event.target as HTMLInputElement).value})"></label><label>X 轴标题<input class="field" :value="settings.xAxisTitle" placeholder="可选" @input="emit('change',{xAxisTitle:($event.target as HTMLInputElement).value})"></label><label>Y 轴标题<input class="field" :value="settings.yAxisTitle" placeholder="可选" @input="emit('change',{yAxisTitle:($event.target as HTMLInputElement).value})"></label><label>数据来源<input class="field" :value="settings.source" placeholder="例如：内部经营数据" @input="emit('change',{source:($event.target as HTMLInputElement).value})"></label></section></template></aside></template>
