<script setup lang="ts">
import type { ChartType } from '../types';
import type { ChartSettings, ThemeName } from '../state/project';
import { palettes } from '../charts/config';
const props=defineProps<{settings:ChartSettings;numericColumns:number}>();
const emit=defineEmits<{change:[value:Partial<ChartSettings>]}>();
const types:{value:ChartType;label:string;min:number}[]=[{value:'bar',label:'柱状',min:1},{value:'line',label:'折线',min:1},{value:'pie',label:'饼图',min:1},{value:'doughnut',label:'环形',min:1},{value:'radar',label:'雷达',min:1},{value:'scatter',label:'散点',min:2},{value:'heatmap',label:'热力',min:2},{value:'funnel',label:'漏斗',min:1}];
const themes=Object.keys(palettes) as ThemeName[];
</script>
<template><aside class="property-panel panel-shell"><div class="panel-heading"><div><span class="eyebrow">DESIGN</span><h2>属性</h2></div></div><section class="property-section"><label>图表类型</label><div class="type-grid"><button v-for="item in types" :key="item.value" :disabled="numericColumns<item.min" :class="{active:settings.type===item.value}" @click="emit('change',{type:item.value})">{{ item.label }}</button></div></section><section class="property-section"><label>标题</label><input class="field" :value="settings.title" @input="emit('change',{title:($event.target as HTMLInputElement).value})"></section><section class="property-section"><label>配色</label><div class="palette-grid"><button v-for="theme in themes" :key="theme" :class="{active:settings.theme===theme}" :title="theme" @click="emit('change',{theme})"><i v-for="color in palettes[theme].colors.slice(0,4)" :key="color" :style="{background:color}"></i></button></div></section><section class="property-section toggles"><label><span>显示图例</span><input type="checkbox" :checked="settings.showLegend" @change="emit('change',{showLegend:($event.target as HTMLInputElement).checked})"></label><label><span>图表动画</span><input type="checkbox" :checked="settings.animate" @change="emit('change',{animate:($event.target as HTMLInputElement).checked})"></label><label><span>数据标签</span><input type="checkbox" :checked="settings.showDataLabels" @change="emit('change',{showDataLabels:($event.target as HTMLInputElement).checked})"></label></section></aside></template>
