<script setup lang="ts">
import { computed,onMounted,onUnmounted,ref,watchEffect } from 'vue';
import AppToolbar from './components/AppToolbar.vue';import DataPanel from './components/DataPanel.vue';import ChartCanvas from './components/ChartCanvas.vue';import PropertyPanel from './components/PropertyPanel.vue';import StatusBar from './components/StatusBar.vue';import ExportDialog from './components/ExportDialog.vue';
import { createCsv,createPdf,renderChartImage,type ExportOptions } from './export/exporter';
import { useProjectState,type AppTheme,type ChartSettings } from './state/project';
import { copyText,getRecentProjects,importWorkbook,loadDraft,openProject,rememberRecent,saveDraft,saveExportFile,saveProject,type ImportedSheet,type ProjectDocument } from './platform/native';

const state=useProjectState(),chart=ref<InstanceType<typeof ChartCanvas>>(),currentPath=ref<string|null>(null),projectName=ref('未命名项目'),notice=ref('');
const importSheets=ref<ImportedSheet[]>([]),importName=ref(''),recentProjects=ref<string[]>([]),showRecent=ref(false),showExport=ref(false);let draftTimer:number|undefined;
const errorCount=computed(()=>state.issues.value.filter(i=>i.level==='error').length);
const fileLabel=computed(()=>currentPath.value?.split(/[\\/]/).pop()||projectName.value);
function applyTheme(value:AppTheme){state.setTheme(value);}watchEffect(()=>{document.documentElement.dataset.theme=state.appTheme.value;});
watchEffect(()=>{JSON.stringify([state.table.value,state.settings]);window.clearTimeout(draftTimer);draftTimer=window.setTimeout(()=>{if(!state.saved.value)void saveDraft(documentValue());},800);});
function changeSettings(value:Partial<ChartSettings>){Object.assign(state.settings,value);state.saved.value=false;}
function documentValue():ProjectDocument{return{schemaVersion:1,metadata:{name:projectName.value,updatedAt:new Date().toISOString()},data:JSON.parse(JSON.stringify(state.table.value)),chart:JSON.parse(JSON.stringify(state.settings))};}
async function handleImport(path?:string){try{const workbook=await importWorkbook(path);if(!workbook)return;importName.value=workbook.name;if(workbook.sheets.length===1)applySheet(workbook.sheets[0]);else importSheets.value=workbook.sheets;}catch(error){showNotice(`导入失败：${message(error)}`,true);}}
function applySheet(sheet:ImportedSheet){state.loadTable({headers:sheet.headers,rows:sheet.rows});projectName.value=importName.value.replace(/\.[^.]+$/,'')||sheet.name;importSheets.value=[];showNotice(`已导入工作表：${sheet.name}`);}
async function openRecent(path:string){currentPath.value=path;await handleOpenPath(path);}
async function handleOpenPath(path:string){try{const {invoke}=await import('@tauri-apps/api/core');const contents=await invoke<string>('read_text_file',{path});const {parseProject}=await import('./platform/native');const document=parseProject(contents);state.loadProject(document.data,document.chart);currentPath.value=path;projectName.value=document.metadata.name;await rememberRecent(path);recentProjects.value=await getRecentProjects();showNotice('最近项目已打开');}catch(error){showNotice(`打开失败：${message(error)}`,true);}}
async function handleOpen(){try{const opened=await openProject();if(!opened)return;state.loadProject(opened.document.data,opened.document.chart);currentPath.value=opened.path;projectName.value=opened.document.metadata.name||'未命名项目';if(opened.path)await rememberRecent(opened.path);recentProjects.value=await getRecentProjects();showNotice('项目已打开');}catch(error){showNotice(`打开失败：${message(error)}`,true);}}
async function handleSave(saveAs=false){try{const path=await saveProject(documentValue(),currentPath.value,saveAs);if(path){currentPath.value=path;await rememberRecent(path);recentProjects.value=await getRecentProjects();}state.markSaved();showNotice('项目已保存');}catch(error){showNotice(`保存失败：${message(error)}`,true);}}
async function handleExport(options:ExportOptions){try{if(state.hasErrors.value)return showNotice('请先修复数据错误再导出',true);let contents:string,extension:'png'|'pdf'|'csv'=options.format;if(options.format==='csv'){contents=createCsv(state.table.value);}else{const image=await renderChartImage(state.table.value,state.settings,options);contents=options.format==='pdf'?createPdf(image,options.width,options.height):image;}const ok=await saveExportFile(contents,`${options.fileName}.${extension}`,extension);if(ok){showExport.value=false;showNotice(`${extension.toUpperCase()} 已导出`);}}catch(error){showNotice(`导出失败：${message(error)}`,true);}}
async function handleCopy(){const text=`${state.settings.title}${state.settings.subtitle?`\n${state.settings.subtitle}`:''}\n${state.table.value.rows.length} 行数据，${state.table.value.headers.length-1} 个指标${state.settings.source?`\n数据来源：${state.settings.source}`:''}`;try{await copyText(text);showNotice('摘要已复制');}catch(error){showNotice(`复制失败：${message(error)}`,true);}}
function handleReset(){if(!state.saved.value&&!confirm('当前项目有未保存更改，仍要新建吗？'))return;state.reset();currentPath.value=null;projectName.value='未命名项目';}
function showNotice(text:string,error=false){notice.value=text;window.setTimeout(()=>{if(notice.value===text)notice.value='';},error?4500:2600);}function message(error:unknown){return error instanceof Error?error.message:String(error);}
function keydown(event:KeyboardEvent){const mod=event.ctrlKey||event.metaKey;if(!mod)return;const key=event.key.toLowerCase();if(key==='z'){event.preventDefault();event.shiftKey?state.redo():state.undo();}else if(key==='y'){event.preventDefault();state.redo();}else if(key==='s'){event.preventDefault();void handleSave(event.shiftKey);}else if(key==='o'){event.preventDefault();void handleOpen();}}
function beforeUnload(event:BeforeUnloadEvent){if(!state.saved.value){event.preventDefault();event.returnValue='';}}
onMounted(async()=>{window.addEventListener('keydown',keydown);window.addEventListener('beforeunload',beforeUnload);recentProjects.value=await getRecentProjects();const draft=await loadDraft();if(draft&&confirm('发现自动保存的草稿，是否恢复？')){state.loadProject(draft.data,draft.chart);state.saved.value=false;projectName.value=draft.metadata.name;}if('__TAURI_INTERNALS__' in window){const {getCurrentWebview}=await import('@tauri-apps/api/webview');await getCurrentWebview().onDragDropEvent(event=>{if(event.payload.type==='drop'){const path=event.payload.paths[0];if(path){if(/\.(t2c|json)$/i.test(path))void handleOpenPath(path);else void handleImport(path);}}});}});onUnmounted(()=>{window.removeEventListener('keydown',keydown);window.removeEventListener('beforeunload',beforeUnload);window.clearTimeout(draftTimer);});
</script>
<template><div class="app-frame"><AppToolbar :can-undo="Boolean(state.undoStack.value.length)" :can-redo="Boolean(state.redoStack.value.length)" :saved="state.saved.value" :theme="state.appTheme.value" :file-name="fileLabel" @undo="state.undo" @redo="state.redo" @reset="handleReset" @open="handleOpen" @recent="showRecent=!showRecent" @save="handleSave(false)" @save-as="handleSave(true)" @export="showExport=true" @copy="handleCopy" @theme="applyTheme"/><div class="workspace-grid"><DataPanel :table="state.table.value" :raw="state.rawInput.value" :issues="state.issues.value" @update:raw="state.rawInput.value=$event" @parse="state.parseRaw" @import="handleImport()" @cell="state.updateCell" @header="state.renameColumn" @add-row="state.addRow" @delete-rows="state.deleteRows" @add-column="state.addColumn" @delete-column="state.deleteColumn"/><ChartCanvas ref="chart" :table="state.table.value" :settings="state.settings" :zoom="state.zoom.value" :has-errors="state.hasErrors.value"/><PropertyPanel :settings="state.settings" :numeric-columns="state.table.value.headers.length-1" @change="changeSettings"/></div><StatusBar :rows="state.table.value.rows.length" :cols="state.table.value.headers.length" :errors="errorCount" :saved="state.saved.value" :zoom="state.zoom.value" @zoom="state.zoom.value=$event"/><ExportDialog v-if="showExport" :project-name="projectName" @close="showExport=false" @export="handleExport"/><div v-if="notice" class="native-notice">{{notice}}</div><div v-if="importSheets.length" class="modal-backdrop" @click.self="importSheets=[]"><section class="sheet-dialog"><header><div><span class="eyebrow">WORKBOOK</span><h3>选择工作表</h3></div><button @click="importSheets=[]">×</button></header><p>{{importName}} 包含 {{importSheets.length}} 个工作表</p><button v-for="sheet in importSheets" :key="sheet.name" class="sheet-option" @click="applySheet(sheet)"><strong>{{sheet.name}}</strong><span>{{sheet.rows.length}} 行 × {{sheet.headers.length}} 列</span></button></section></div><aside v-if="showRecent&&recentProjects.length" class="recent-projects"><span>最近项目</span><button v-for="path in recentProjects.slice(0,3)" :key="path" :title="path" @click="openRecent(path)">{{path.split(/[\\/]/).pop()}}</button></aside></div></template>
